### ISSUE TITLE
"not intended for synthesis"

### ISSUE THREAD

**Issue by taylor-bsg** [lewiz-support/LMAC_CORE3#2]
Hi, in the README, it says "this release is not intended for synthesis". What does that mean? What parts do not currently synthesize? Is there a date at which the synthesizable version will be released?

Thanks!

**Comment by lewiz-support** [comment]
The released code is technology independent. Its FIFOs are generic. You need to replace them with technology specific FIFO for the core to synthesize. The synthesizable versions for all 3 LeWiz LMAC cores targeting for FPGA technology will be available by June 2020 if not earlier.

**Comment by taylor-bsg** [comment]
Ah I see. You could use the async fifos from BaseJump STL:

https://github.com/taylor-bsg/basejump_stl/blob/master/bsg_async/bsg_async_fifo.v

M

**Comment by taylor-bsg** [comment]
@hellokayt

**Comment by lewiz-support** [comment]
Thank you for the info.
We will release the synthesized version so the current code released is intended for RTL development.
For FPGA chip implementations, the users will use FIFOs from the FPGA vendors anyway. These FIFOs would be generated from vendors' tools for specific FPGA family.
For ASIC implementation, the users would use FIFOs from ASIC vendors. These are usually specific to ASIC silicon process.
Since these are technology dependent, we opted to release code technology independent. This way we can keep things in open source.

**Comment by taylor-bsg** [comment]
Usually ASIC vendors do not provide FIFOs — but they do provide the SRAM
generator for 1R1W rams. The BaseJump STL asynchronous fifo is designed to
allow the user to swap in their own hardened SRAMs. The only tricky part
are the timing assertions that have to be added, but we provide those as
well.

**Comment by lewiz-support** [comment]
Thanks for pointing that out.
ASIC is process and vendor dependent. The FIFO support is dependent on vendor specific tool.
We will keep what you said in mind for future releases. 
Right now, our focus is to get FPGA versions out.
